### ISSUE TITLE
Add python script selection in argparse

### ISSUE THREAD

**Issue by nim65s** [Gepetto/gepetuto#10]
with a `-f` / `--file` argparse argument, instead of blindly acting on all of them everytime.

This will be useful for #6

**Comment by TheoMF** [comment]
just to be sure, if someone use -f and tp_id, we should apply the action to both the files with the -f and the files in the tp_id folders ?

**Comment by nim65s** [comment]
yes

**Comment by nim65s** [comment]
this "and" might be a quiproquo.
`tp_id` and `file` are filters. when they are both specified, we should only act on files where `tp_id` and `file` match.
