### ISSUE TITLE
unit testing the cli arguments

### ISSUE THREAD

**Issue by nim65s** [Gepetto/gepetuto#31]
If we have the following structure:
```
├── 1_example_notebook.ipynb
├── 2_other_notebook.ipynb
├── tp1
│   ├── cholesky.py
│   └── example_script.py
└── tp2
    ├── cholesky.py
    └── something.py
```

- with no tp_id and no file, we should find all 4 python files
- with tp_id=1 and no file, we should get the 2 python files in tp1
- with no tp_id and file=tp1/cholesky.py, we should get 1 python file in tp1
- with tp_id=1 and file=tp1/cholesky.py, we should get 1 python file in tp1
- with tp_id=2 and file=tp1/cholesky.py, we should get 0 python files

We should write unit tests to check this

_Originally posted by @nim65s in https://github.com/Gepetto/gepetuto/pull/24#discussion_r1281947935_

**Comment by nim65s** [comment]
For this, we'll have to : 
1. add the missing files from this example into the tests/ directory
2. move the tp_id + file + filter logic in the main file (following what was done on tp_id in #9)
3. update the `parse_args()` function to add an `args=None` argument, and forward this to `parser.parse_args(args=args)`
4. write 5 unit-tests for this 5 cases by calling eg. `parse_args(['gepetuto', '-f', 'tp1/cholesky.py', '1'])` and check the return of this function

**Comment by TheoMF** [comment]
> For this, we'll have to :
> 
>     1. add the missing files from this example into the tests/ directory
> 
>     2. move the tp_id + file + filter logic in the main file (following what was done on tp_id in [Move tp_id detection logic into __main__.py #9](https://github.com/Gepetto/gepetuto/issues/9))
> 
>     3. update the `parse_args()` function to add an `args=None` argument, and forward this to `parser.parse_args(args=args)`
> 
>     4. write 5 unit-tests for this 5 cases by calling eg. `parse_args(['gepetuto', '-f', 'tp1/cholesky.py', '1'])` and check the return of this function

I have a doubt, should we look for the output of the command `gepetuto', '-f', 'tp1/cholesky.py', '1'` or look at the args output of the function `parse_args()` in `__main__.py`

**Comment by nim65s** [comment]
I see. Then we'll need an intermediate function to transform our tp_id + file + filter input from the command line to our `parse_args()` function and then from the output of that one to a tp_id + file list.
I guess we'll also have to remove the default arguments for tp_id, and compute this list from that new function only if needed.
